server:
  port: 8080

aliyun:
  appKey: 25418637
  appSecret: e4d0262babdb78eb892d5fc100fbd32c
  productKey: a16IzBxrD85

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${iot.hosting.rds.datasource.mysqlUrl}:3306/upstream?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${iot.hosting.rds.datasource.mysqlUser}
    password: ${iot.hosting.rds.datasource.mysqlPassword}
    schema: classpath:schema.sql
    initialize: true
    continueOnError: true
    initialization-mode: always