server:
  port: 8080

aliyun:
  appKey: ${iot.hosting.appKey}
  appSecret: ${iot.hosting.appSecret}
  accessKey: ${iot.hosting.accessKey}
  accessSecret: ${iot.hosting.accessSecret}
  productKey: a16IzBxrD85

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${iot.hosting.rds.storage.mysqlUrl}:3306/storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${iot.hosting.rds.storage.mysqlUser}
    password: ${iot.hosting.rds.storage.mysqlPassword}
    schema: classpath:schema.sql
    initialize: true
    continueOnError: true
    initialization-mode: always
    
logging:
  config: classpath:log4j2.xml